os: osx
osx_image: xcode10.2
language: objective-c
#branches:
#  only:
#    - master
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - WORKSPACE=Example/SwiftAI.xcworkspace
  - EXAMPLE_SCHEME="SwiftAI-Example"
  matrix:
    - DESTINATION="OS=12.2,name=iPhone XS"       SCHEME="$EXAMPLE_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES"
    - DESTINATION="OS=11.4,name=iPhone X"        SCHEME="$EXAMPLE_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus" SCHEME="$EXAMPLE_SCHEME" RUN_TESTS="YES" BUILD_EXAMPLE="YES"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks

  # Build Example in Release and Run Tests if specified
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
    else
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  # Build Example in Debug if specified
  - if [ $BUILD_EXAMPLE == "YES" ]; then
      xcodebuild -workspace "$WORKSPACE" -scheme "$EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;
    fi

  - pod lib lint
